---
- name: Deploy WAR from Nexus to Docker
  hosts: dockerhost
  become: true

  vars:
    app_dir: /home/ansibleadmin

  tasks:

  - name: Download latest WAR from Nexus
    get_url:
      url: "http://{{ nexus_ip }}:8081/service/rest/v1/search/assets/download?sort=version&repository=MyLab-RELEASE&maven.groupId=com.mylab&maven.artifactId=MyLab&maven.extension=war"
      dest: "{{ app_dir }}/latest.war"
      url_username: "{{ nexus_user }}"
      url_password: "{{ nexus_pass }}"

  - name: Create Dockerfile
    copy:
      dest: "{{ app_dir }}/Dockerfile"
      content: |
        FROM tomcat:latest
        ADD latest.war /usr/local/tomcat/webapps/
        EXPOSE 8080
        CMD ["catalina.sh", "run"]

  - name: Build Docker Image
    docker_image:
      name: mylab-image
      path: "{{ app_dir }}"
      state: present

  - name: Run Container
    docker_container:
      name: mylab-container
      image: mylab-image
      state: started
      recreate: yes
      ports:
        - "8080:8080"